name: 'Honkai: Star Rail Daily Check In'
on:
  schedule:
    # Every day at 00:05(UTC+8)
    - cron: '5 16 * * *'
  workflow_dispatch:

jobs:
  hsr-daily-check-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm playwright install --with-deps
      - name: Build
        run: pnpm build
      - name: Run daily check in script
        run: pnpm start
        env:
          LTOKEN: ${{ secrets.LTOKEN }}
          LTUID: ${{ secrets.LTUID }}
          LANG: ${{ vars.LANG }}
